### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by yug-delemont** [zararashraf/youtube-video-downloader-api#4]
## We are try to get the information using this repo code but getting below error.

```bash
{
    "error": "<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>"
}
```
![image](https://github.com/user-attachments/assets/62a34862-62b5-46c3-bc00-aabeae1f4574)

**Comment by zararashraf** [comment]
Hi Yug,
Thanks for reaching out to me, I'm at the office right now without my PC.
It could be possible that url you are sending in the post request is not
supported. Try removing the pp part.

**Comment by yug-delemont** [comment]
No, it's not work.
